import { InjectionToken } from '@angular/core';

export const Icons = new InjectionToken<ReadonlyArray<string>>('Icons');

export const ICONS: ReadonlyArray<string> = [
  'accessibility',
  'account_balance',
  'account_balance_wallet',
  'account_circle',
  'alarm',
  'all_inbox',
  'assessment',
  'assignment',
  'autorenew',
  'bookmark',
  'bug_report',
  'build',
  'card_giftcard',
  'commute',
  'date_range',
  'delete',
  'face',
  'favorite',
  'fingerprint',
  'flight_takeoff',
  'grade',
  'home',
  'motorcycle',
  'pets',
  'receipt',
  'room',
  'shopping_cart',
  'watch_later',
  'work',
  'mic',
  'radio',
  'call',
  'email',
  'gesture',
  'weekend',
  'waves',
  'format_paint',
  'attachment',
  'photo_camera',
  'style',
  'directions_car',
  'local_bar',
  'local_cafe',
  'local_dining',
  'local_drink',
  'terrain',
  'cake',
  'school',
];
